{% set name = "mlx-ctc" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mlx_ctc-{{ version }}.tar.gz
  sha256: a6bd060a3b0ea54a208b2d5d0b112684968c04454b49c1fb890e00294b41d02b

build:
  skip: true  # [py<39 or not (linux or (osx and arm64))]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake >=3.24
    - make
  host:
    - python
    - setuptools >=42
    - mlx >=0.10.0
    - nanobind
    - pip
    - libblas  # [linux]
  run:
    - python
    - mlx >=0.10.0

test:
  imports:
    - mlx_ctc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/djphoenix/mlx-ctc
  summary: C++ and Metal extensions for MLX CTC Loss
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
